### ISSUE TITLE
Restyle logo

### ISSUE THREAD

**Issue by DuongNManh** [lcaohoanq/Clothes-Shop#12]
Logo.png to transperant
![image](https://github.com/lcaohoanq/Clothes-Shop/assets/152079455/a9fb707d-3677-44a4-a566-436f84762c79)

**Comment by lcaohoanq** [comment]
@DuongNManh okay, i will do it now

**Comment by lcaohoanq** [comment]
Done at 
- https://github.com/lcaohoanq/Clothes-Shop/pull/13
